### ISSUE TITLE
Bot is failing to authenticate

### ISSUE THREAD

**Issue by Semior001** [Drop-Team/InnoID-API#1]
After passing the oauth url, it redirects me to the bot page, which responds me with:
> 😕 You are not logged in, so we do not store your data.

telegram id: 158606457, username: @semior001

I'd rather suggest to add log messages for that cases:
- [in here](https://github.com/Drop-Team/InnoID/blob/462bc9115bff2a1cf3d1429b32d426e5eaf71c46/Telegram-Bot/bot/loops/event.py#L39)
- [in here](https://github.com/Drop-Team/InnoID/blob/462bc9115bff2a1cf3d1429b32d426e5eaf71c46/Telegram-Bot/bot/loops/event.py#L50)
- and [in here](https://github.com/Drop-Team/InnoID/blob/462bc9115bff2a1cf3d1429b32d426e5eaf71c46/Telegram-Bot/bot/loops/event.py#L57)

as it's impossible to understand neither for client and for a developer where the error has occured and what's missing in the response

**Comment by ekuziakov** [comment]
Resolved
